export default function sitemap() {
  const articles = [
    'comment-vendre-en-live-sur-tiktok',
    'live-shopping-quel-outil-paiement-choisir',
    'detecter-commandes-automatiquement-live-tiktok',
    'encaisser-ventes-live-tiktok-sans-commission',
    'creer-boutique-live-shopping-sans-site-ecommerce',
    'mondial-relay-etiquette-vendeuse-live',
    'pourquoi-live-shopping-explose-france-2026',
    'je-prends-tiktok-live-gerer-commandes',
    'alternative-buylive-sans-commission',
    'buylive-vs-mylivepaiement-comparatif',
    'livepaye-alternative-avis-comparatif',
    'meilleur-outil-paiement-live-tiktok-france',
    'comment-eviter-arnaques-paiement-live-shopping',
    'perdre-commandes-live-tiktok-solutions',
    'vendre-cosmetiques-live-tiktok-guide',
    'vendre-vetements-live-shopping-mode',
    'vendre-bijoux-accessoires-live-tiktok',
    'configurer-page-paiement-live-shopping',
    'lien-bio-tiktok-paiement-live',
    'materiel-necessaire-live-shopping-tiktok',
    'premier-live-tiktok-shopping-etapes',
    'combien-gagner-live-shopping-tiktok',
    'vivre-live-shopping-tiktok-revenu-principal',
    'tiktok-shop-france-2026-live-shopping',
    'tendances-live-shopping-2026-france',
    'stripe-paiement-vendeuse-live-tiktok',
    'point-relais-mondial-relay-live-shopping',
    'erreurs-debutante-live-shopping-eviter',
    'augmenter-panier-moyen-live-tiktok',
    'fidéliser-clientes-live-shopping',
    'live-shopping-instagram-vs-tiktok',
    'comment-preparer-stock-live-shopping',
    'auto-entrepreneur-live-shopping-statut',
    'creer-urgence-live-shopping-vendre-plus',
    'relancer-clientes-apres-live-tiktok',
    'live-shopping-facebook-marketplace-2026',
    'emballage-colis-live-shopping-conseils',
    'gerer-commentaires-negatifs-live-tiktok',
    'optimiser-profil-tiktok-live-shopping',
    'comptabilite-vendeuse-live-tiktok',
    'live-shopping-dropshipping-difference',
    'meilleurs-horaires-live-tiktok-france',
    'retours-remboursements-live-shopping',
    'algorithme-tiktok-live-shopping-2026',
    'paiement-en-plusieurs-fois-live-shopping',
    'temoignage-vendeuse-live-shopping-reussite',
    'live-shopping-noel-black-friday-strategie',
    'securite-paiement-live-shopping-stripe',
    'creer-offres-irresistibles-live-shopping',
    'vendre-sans-followers-tiktok-live',
  ]

  return [
    {
      url: 'https://www.mylivepaiement.com',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
    },
    {
      url: 'https://www.mylivepaiement.com/blog',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    ...articles.map(slug => ({
      url: 'https://www.mylivepaiement.com/blog/' + slug,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    })),
    {
      url: 'https://www.mylivepaiement.com/dashboard',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.5,
    },
  ]
}
